### ISSUE TITLE
RWD problems 

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/sat4envi#840]
1. done
 ![obraz](https://user-images.githubusercontent.com/59872096/97224348-4e0cd680-17d1-11eb-9853-639ccbfe12ec.png)

2. done ![image](https://user-images.githubusercontent.com/59872096/101459871-15682d00-3939-11eb-87f9-41607a25449c.png)

3. done
 ![obraz](https://user-images.githubusercontent.com/59872096/97225851-7990c080-17d3-11eb-9f5b-aadcf5ec60fa.png)

4. done
![obraz](https://user-images.githubusercontent.com/59872096/97224694-cffcff80-17d1-11eb-9d32-0c4827a57f70.png)

5. done
 ![obraz](https://user-images.githubusercontent.com/59872096/97224851-05a1e880-17d2-11eb-99e0-be5817ac2126.png)

6. done
 ![obraz](https://user-images.githubusercontent.com/59872096/97224941-3124d300-17d2-11eb-9f28-5c9bbc4c1fc9.png)

7. done
 ![obraz](https://user-images.githubusercontent.com/59872096/97225235-ae504800-17d2-11eb-8b2f-5d3fbe6b6321.png)

8. done
![obraz](https://user-images.githubusercontent.com/59872096/97225302-c7f18f80-17d2-11eb-828c-4597505be308.png)

9. done
![obraz](https://user-images.githubusercontent.com/59872096/97225456-f3747a00-17d2-11eb-974a-bd287e3cc470.png)

10. done
 ![obraz](https://user-images.githubusercontent.com/59872096/97225500-07b87700-17d3-11eb-9bdb-ec39c746f63c.png)

11.done
 ![obraz](https://user-images.githubusercontent.com/59872096/97225624-2a4a9000-17d3-11eb-8869-51c121d288f3.png)

12. done
 ![image](https://user-images.githubusercontent.com/59872096/101460009-4c3e4300-3939-11eb-88d9-80d08118f7d2.png)

13.
 ![image](https://user-images.githubusercontent.com/59872096/101460136-7abc1e00-3939-11eb-9668-c9fae9a9f6ce.png)
14. 
 ![image](https://user-images.githubusercontent.com/59872096/101460304-b656e800-3939-11eb-97a5-2690e67c5ff4.png)
15. done
![image](https://user-images.githubusercontent.com/59872096/101460518-fc13b080-3939-11eb-8fa3-95f6a7259dac.png)
16. done
![image](https://user-images.githubusercontent.com/59872096/101467785-130ad080-3943-11eb-8fec-b8db49ff4644.png)

**Comment by abacz** [comment]
@Marcelinna I think i've already fixed everything.

**Comment by Marcelinna** [comment]
@abacz  Problem 2 still exist and now I added 13, 14 , 15 , 16

**Comment by abacz** [comment]
Ive fixed 2,12,16 in #999

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK

**Comment by Marcelinna** [comment]
It isnt possible choose every date
17. ![image](https://user-images.githubusercontent.com/59872096/106130206-5f170c00-6161-11eb-8b67-a1fa22d1e42a.png)

**Comment by Marcelinna** [comment]
18. ![image](https://user-images.githubusercontent.com/59872096/106130394-92f23180-6161-11eb-8f01-f2e46d31fea1.png)

**Comment by Marcelinna** [comment]
It isn't possible download files, and layer icon covered button <_powrot do formularza>
19. ![image](https://user-images.githubusercontent.com/59872096/106130550-c7fe8400-6161-11eb-9352-607a6aa04a5c.png)

**Comment by Marcelinna** [comment]
20, ![obraz](https://user-images.githubusercontent.com/59872096/106133192-36911100-6165-11eb-9462-571396bd2bae.png)

**Comment by abacz** [comment]
14, 17, 18, 19 -> https://github.com/cyfronet-fid/sat4envi/pull/1125

**Comment by Marcelinna** [comment]
20. Problem still exist 17.2.1-RELEASE
![image](https://user-images.githubusercontent.com/59872096/108177433-88dda600-7103-11eb-99e8-05b4e91456cc.png)

**Comment by Marcelinna** [comment]
21. still exist 17.2.1-RELEASE
![image](https://user-images.githubusercontent.com/59872096/108177796-f38ee180-7103-11eb-9d27-4fcfd548c353.png)
